name: Android CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Store Gradle Binnary
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Store Gradle Caches
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build debug APK
        run: bash ./gradlew :app:assembleDemoDebug :app:assembleFullDebug -PprojectAllowHttpProxy=true --stacktrace
      - name: Upload Demo APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/demo/debug/app-demo-debug.apk
      - name: Upload Full APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/full/debug/app-full-debug.apk
